services:
  xsbh-frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: xsbh-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./user-fragments:/app/data/fragments
    restart: unless-stopped
    depends_on:
      - xsbh-backend

  xsbh-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: xsbh-backend
    ports:
      - "8111:8111"
    volumes:
      - ./data:/app/data
      - ./user-fragments:/app/data/fragments
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
